### ISSUE TITLE
bug not working

### ISSUE THREAD

**Issue by XXX10Tacles** [magnusulf/Factions#1]
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** v3.0.3

Server version: [17:31:05 INFO]: This server is running CraftBukkit version git-Spigot-f56e2e7-7fc66b2 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[17:31:05 INFO]: Checking version, please wait...
[17:31:06 INFO]: You are running the latest version

Plugin crashes at startup: `[17:29:19 INFO]: FAILURE FOR CLASS: class com.massivecraft.factions.entity.MPlayer
[17:29:19 ERROR]: Error occurred while enabling Factions v3.0.3 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.factions.entity.migrator.MigratorMPlayer001Ranks.migrateInner(MigratorMPlayer001Ranks.java:32) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorRoot.migrate(MigratorRoot.java:117) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateClass(MigratorUtil.java:322) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateObject(MigratorUtil.java:238) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrate(MigratorUtil.java:192) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:307) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:799) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:950) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:989) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:247) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:235) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:211) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:128) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`
```

**Comment by XXX10Tacles** [comment]
plugin is working fine if it creates mstore files by himself.

**Comment by magnusulf** [comment]
I see the problem is with the migrator, so it makes sense that it works fine if it creates the files by itself.
What version are you updating from?

Could you please try to run the server again with the same files and the linker version of MassiveCore. It contains some hopefully useful debug information.
https://www.dropbox.com/s/ezn2zcdjjcvwa8a/MassiveCore.jar?dl=0

**Comment by XXX10Tacles** [comment]
Name: Factions
 Version: 2.14.0

normal factions had errors with worldguard integration so i downloaded somwhere where that integration was disabled or removed idk where that was but i lil try to find that link.


`[17:55:46 INFO]: Problem with migrating entity:
[17:55:46 INFO]: {"lastActivityMillis":1547318888359,"power":1.7999999999999998}
[17:55:46 INFO]: FAILURE FOR CLASS: class com.massivecraft.factions.entity.MPlayer
[17:55:46 ERROR]: Error occurred while enabling Factions v3.0.3 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.factions.entity.migrator.MigratorMPlayer001Ranks.migrateInner(MigratorMPlayer001Ranks.java:32) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorRoot.migrate(MigratorRoot.java:120) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateClass(MigratorUtil.java:322) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateObject(MigratorUtil.java:238) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrate(MigratorUtil.java:192) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:307) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:799) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:950) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:989) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:247) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:235) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:211) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:128) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

**Comment by XXX10Tacles** [comment]
sadly i cant fint link :(

**Comment by magnusulf** [comment]
This version of Factions ought to fix it :-) 
Please tell me if it does.
https://www.dropbox.com/s/gyzt96v1s8nb52q/Factions.jar?dl=0

If it works I will upload it to Spigot later.

**Comment by XXX10Tacles** [comment]
`[18:32:35 INFO]: [Factions] Enabling Factions v3.0.3
[18:32:35 INFO]: [Factions 3.0.3] === ENABLE START ===
[18:32:35 INFO]: [Factions 3.0.3] Activated FactionColl
[18:32:35 INFO]: Problem with migrating entity:
[18:32:35 INFO]: {"lastActivityMillis":1547318888359,"power":1.7999999999999998}
[18:32:35 INFO]: FAILURE FOR CLASS: class com.massivecraft.factions.entity.MPlayer
[18:32:35 ERROR]: Error occurred while enabling Factions v3.0.3 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.factions.entity.migrator.MigratorMPlayer001Ranks.migrateInner(MigratorMPlayer001Ranks.java:49) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorRoot.migrate(MigratorRoot.java:120) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateClass(MigratorUtil.java:322) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateObject(MigratorUtil.java:238) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrate(MigratorUtil.java:192) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:307) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:799) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:950) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:989) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:247) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:235) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:211) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:128) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

**Comment by XXX10Tacles** [comment]
got same error

**Comment by magnusulf** [comment]
Woops, sorry.
Try this one: https://www.dropbox.com/s/3ja0kzx5bhf8m6q/Factions.jar?dl=0

**Comment by XXX10Tacles** [comment]
`[18:44:55 INFO]: [Factions 3.0.3] === ENABLE START ===
[18:44:55 INFO]: [Factions 3.0.3] Activated FactionColl
[18:44:55 INFO]: Problem with migrating entity:
[18:44:55 INFO]: {"lastActivityMillis":1547714410309,"factionId":"8ad16276-c5f3-4ff8-84ee-2efb4b4409b9","power":2.666666666666671}
[18:44:55 INFO]: FAILURE FOR CLASS: class com.massivecraft.factions.entity.MPlayer
[18:44:55 ERROR]: Error occurred while enabling Factions v3.0.3 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.factions.entity.migrator.MigratorMPlayer001Ranks.migrateInner(MigratorMPlayer001Ranks.java:65) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorRoot.migrate(MigratorRoot.java:120) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateClass(MigratorUtil.java:322) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrateObject(MigratorUtil.java:238) ~[?:?]
        at com.massivecraft.massivecore.store.migrator.MigratorUtil.migrate(MigratorUtil.java:192) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.loadFromRemoteFixed(Coll.java:307) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:799) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:950) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:989) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:247) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:226) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:235) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activate(MassivePlugin.java:211) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateAuto(MassivePlugin.java:324) ~[?:?]
        at com.massivecraft.factions.Factions.onEnableInner(Factions.java:128) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:82) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-7fc66b2]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]`

**Comment by XXX10Tacles** [comment]
also i uploaded files on dropbox so u can look in.
https://www.dropbox.com/s/ox270c6i2cid5vh/mstore.rar?dl=0

**Comment by magnusulf** [comment]
Could you tell me what faction the player with the id "52d243b9-b750-3ef8-a4c8-e172d7686127" is supposed to be in?

**Comment by XXX10Tacles** [comment]
wierd, i found that player
`{
  "lastActivityMillis": 1547714410309,
  "factionId": "8ad16276-c5f3-4ff8-84ee-2efb4b4409b9",
  "power": 2.666666666666671
}`
but cant find that faction (8ad16276-c5f3-4ff8-84ee-2efb4b4409b9) in files.

**Comment by magnusulf** [comment]
Yeah, I got the same. I was wondering if some database bug had occured so your files are inaccurate, or if the player simply is not part of any faction.

**Comment by magnusulf** [comment]
You can try this one: https://www.dropbox.com/s/i9mlluwihmbtf2d/Factions.jar?dl=0

If it cant find a faction for someone it assumes they are member of Wilderness.

**Comment by XXX10Tacles** [comment]
yep working fine <3 ty alot ;)
