### ISSUE TITLE
Craft Scheduler Thread exception

### ISSUE THREAD

**Issue by LiLPandemio** [magnusulf/Factions#104]
## Affected Plugin
Factions3 3.3.3

massive core version

Name: MassiveCore
Version: 3.3.3
Website: https://www.muj.dk/massivecore
Authors: Madus, Cayorion and Ulumulu1510
Description: MassiveCore is a plugin that contains libraries and features that other plugins make use of.

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.3.3

## Describe your Environment

- **Server Version:** ???
This server is running CraftBukkit version git-Spigot-cbd1a1b-009d8af (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

## Steps to Reproduce this Bug
Suddenly started spamming the exception below every 3-5 seconds or so.

## Observed Results

Exception nullpointer.

[Craft Scheduler Thread - 925/WARN]: [Factions] Plugin Factions v3.3.3 generated an exception while executing task 103
java.lang.NullPointerException: element cannot be mapped to a null key
        at java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
        at java.util.stream.Collectors.lambda$groupingBy$53(Collectors.java:1127) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.concurrent.ConcurrentSkipListMap$EntrySpliterator.forEachRemaining(ConcurrentSkipListMap.java:3334) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.massivecraft.factions.entity.Board.getFactionToChunks(Board.java:171) ~[?:?]
        at com.massivecraft.factions.entity.BoardColl.lambda$getWorldToFactionToChunks$2(BoardColl.java:195) ~[?:?]
        at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:178) ~[?:?]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3605) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
        at com.massivecraft.factions.entity.BoardColl.getWorldToFactionToChunks(BoardColl.java:195) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.createAreas(EngineDynmap.java:192) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.perform(EngineDynmap.java:93) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.run(EngineDynmap.java:77) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.14.4.jar:git-Spigot-cbd1a1b-009d8af]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:835) [?:?]

## Expected Results
Not to spam console, everything seems to be ok but I don't want my console to be that bad

**Comment by XxXYaJrAbXxX** [comment]
This seems to occur when factions disband and fails to clean all references of the disbanded faction from factions boardcoll properly. As a temporary measure, use `/f clean` when this happens.
