### ISSUE TITLE
cant disband faction

### ISSUE THREAD

**Issue by XXX10Tacles** [magnusulf/Factions#2]
i using last version of massivecore and factions 

i cant disband my faction i getting this error

server version: `[18:20:59] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-f56e2e7-1a64d4a (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)[m
[18:20:59] [Server thread/INFO]: Checking version, please wait...[m
[18:20:59] [Thread-83/INFO]: You are running the latest version[m`

ERROR:
`[18:17:50] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f disband testeri xdsA4S' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.milkbowl.vault.economy.AbstractEconomy.hasAccount(AbstractEconomy.java:10) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.exists(MoneyMixinVault.java:118) ~[?:?]
	at com.massivecraft.massivecore.money.Money.exists(Money.java:100) ~[?:?]
	at com.massivecraft.factions.entity.Faction.preDetach(Faction.java:91) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.preDetach(EntityContainerAbstract.java:348) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.detachFixed(EntityContainerAbstract.java:321) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.detachEntity(EntityContainerAbstract.java:299) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.detachEntity(EntityContainerAbstract.java:16) ~[?:?]
	at com.massivecraft.massivecore.store.Entity.detach(Entity.java:70) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsDisband.perform(CmdFactionsDisband.java:87) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1175) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1131) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:60) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1a64d4a]
	... 14 more`

**Comment by XXX10Tacles** [comment]
i can disband only with command f leave

**Comment by magnusulf** [comment]
What version of Factions and MassiveCore are you using?

**Comment by magnusulf** [comment]
I think I fixed it, but considering every economy plugin is different, please take a look at this and see if it works: https://www.dropbox.com/s/cqu9dq1b5lpbh38/Factions%20econ%20fixed.zip?dl=0

**Comment by XXX10Tacles** [comment]
yea its fixed on 3.0.6
