### ISSUE TITLE
/f claim fill - Error

### ISSUE THREAD

**Issue by halberfan** [magnusulf/Factions#20]
Version: 3.1.4
Server Version: git-Paper-405 (1.13.2)

Just got this error when someone of my players did "/f claim fill"
After I tried it, it worked.

Error:
https://pastebin.com/USaWckrQ

**Comment by magnusulf** [comment]
Do you have WorldGuard on your server? And if so, what version?

**Comment by halberfan** [comment]
Yes, 7.0.0-beta01;01dfebe

**Comment by magnusulf** [comment]
Does this always, never or sometimes happen when you try to claim something that contains a WorldGuard region?
Does this always, never or sometimes happen when you try to claim something that does not contain a WorldGuard region?

**Comment by halberfan** [comment]
So I tested: if its inside a wg region it dosent work, if its not it does work. But I tested booth only one time

**Comment by magnusulf** [comment]
This bug really puzzles me, so I might be grasping straws, but is your WorldGuard version the latest?

Also, you can change "worldguardCheckEnabled" in the config to disable world guard checks, if you want to. I wouldn't consider this a solution at all, but it could be a temporary fix for you.

**Comment by magnusulf** [comment]
Also, do you have WorldEdit installed and what version?

**Comment by halberfan** [comment]
Yes, but I cant tell which version. "unknown"
![2019-02-21](https://user-images.githubusercontent.com/39102685/53186873-30ea3280-3602-11e9-8038-5ba528f8c703.png)

**Comment by magnusulf** [comment]
Try to download the latest WorldEdit and WorldGuard version. I looked at it, and if it is been some time since you updated that might actually be the reason.

**Comment by halberfan** [comment]
btw, because i dont want to do a open a new issue: what does "useNewMoneySystem" do in the config?

**Comment by magnusulf** [comment]
That thing. I didn't think anyone would notice.
Currently money in the faction bank is stored through Vault. But not all economy plugins support that, so it is now possible to convert the system so that money is stored within the Factions plugin instead.

If you are setting up a new server you can safely set "useNewMoneySystem" to "true". Otherwise make a backup of your server and then do "/f moneyconvert" from console. That should be all, but in case something went wrong, then reset from the backup.

**Comment by magnusulf** [comment]
Does it work with the newest WorldEdit and WorldGuard?

**Comment by ghost** [comment]
Command `/f claim fill` return error, when number is over limit of chunks.

``[18:35:22] [Server thread/INFO]: Uran234 issued server command: /f claim fill
[18:35:22] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f claim fill' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-b0f4c22-51c118b]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-b0f4c22-51c118b]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException: pss
        at com.massivecraft.factions.entity.MPlayer.tryClaim(MPlayer.java:801) ~[?:?]
        at com.massivecraft.factions.cmd.CmdFactionsSetX.perform(CmdFactionsSetX.java:54) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1177) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1133) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1133) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:60) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot.jar:git-Spigot-b0f4c22-51c118b]
        ... 14 more
``

**Comment by magnusulf** [comment]
@Uranusak your issue was a different one. it is fixed in the commit abc2782, but next time please make a new issue 😄 I would really prefer five issues too many than one too few.

Also since no response was ever given regarding the original problem, I assume the problem was with WorldGuard, so I am closing this.
