### ISSUE TITLE
Error /f unclaim fill 

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#26]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.5

## Describe your Environment

- **Server Version:** 1.13.2

```
[11:07:38 INFO]: StaGo_Cz issued server command: /f unclaim fill
[11:07:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f unclaim fill' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-cf694d8-8d8475f]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-cf694d8-8d8475f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException: pss
        at com.massivecraft.factions.entity.MPlayer.tryClaim(MPlayer.java:801) ~[?:?]
        at com.massivecraft.factions.cmd.CmdFactionsSetX.perform(CmdFactionsSetX.java:54) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1177) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1133) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1133) ~[?:?]
        at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:60) ~[?:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-cf694d8-8d8475f]
        ... 14 more
```

**Comment by magnusulf** [comment]
This was fixed in abc2782 and will thus be a part of the next update.
