### ISSUE TITLE
f leave

### ISSUE THREAD

**Issue by XXX10Tacles** [magnusulf/Factions#3]
after i use f leave command and if i am alone in clan, clan isn't going to disband. faction still exists but noone is in.

versions: `factions and mcore version: 3.0.6
[09:58:57 INFO]: This server is running CraftBukkit version git-Spigot-f56e2e7-1
748af8 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

ERROR:`09:57:59] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 3.0.6[0;36;22m] [0;33;1mAvTo_ left the faction: test2[m
[09:57:59] [Server thread/INFO]: [0;36;22m[[0;36;1mFactions 3.0.6[0;36;22m] [0;33;1mThe faction test2 (0bdffd11-f3e9-44ef-a40c-27b6b97c2e3b) was disbanded due to the last player (AvTo_) leaving.[m
[09:57:59] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'f leave' in com.massivecraft.massivecore.command.MassiveCoreBukkitCommand(f)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:702) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1636) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1476) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinVault.move(MoneyMixinVault.java:202) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.move(MoneyMixinAbstract.java:64) ~[?:?]
	at com.massivecraft.massivecore.money.MoneyMixinAbstract.set(MoneyMixinAbstract.java:139) ~[?:?]
	at com.massivecraft.massivecore.money.Money.set(Money.java:236) ~[?:?]
	at com.massivecraft.factions.entity.Faction.preDetach(Faction.java:94) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.preDetach(EntityContainerAbstract.java:348) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.detachFixed(EntityContainerAbstract.java:321) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.detachEntity(EntityContainerAbstract.java:299) ~[?:?]
	at com.massivecraft.massivecore.store.EntityContainerAbstract.detachEntity(EntityContainerAbstract.java:16) ~[?:?]
	at com.massivecraft.massivecore.store.Entity.detach(Entity.java:70) ~[?:?]
	at com.massivecraft.factions.entity.MPlayer.leave(MPlayer.java:766) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsLeave.perform(CmdFactionsLeave.java:24) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1175) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCommand.execute(MassiveCommand.java:1131) ~[?:?]
	at com.massivecraft.massivecore.command.MassiveCoreBukkitCommand.execute(MassiveCoreBukkitCommand.java:60) ~[?:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-1748af8]
	... 14 more`

**Comment by magnusulf** [comment]
Please use something like pastebin for the future 😄  Looking at a stack trace in GitHub is not easy 😄 
I am looking into this bug.

**Comment by magnusulf** [comment]
This is economy related and is (hopefully) fixed in 3.0.7
Can you confirm it is fixed in 3.0.7?

**Comment by XXX10Tacles** [comment]
yep fixed
