### ISSUE TITLE
Factions 3.1.5 do not work with spigot 1.14

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#30]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.5

## Describe your Environment

- **Server Version:** Spigot-1.14

```
[12:52:49] [Server thread/INFO]: [Factions] Loading Factions v3.1.5
[12:52:49] [Server thread/INFO]: [MassiveCore] Enabling MassiveCore v3.1.5
[12:52:49] [Server thread/INFO]: [MassiveCore 3.1.5] === ENABLE START ===
[12:52:49] [Server thread/INFO]: [MassiveCore 3.1.5] Loading Cachefile datas...
[12:52:49] [Server thread/INFO]: [MassiveCore 3.1.5] Loading Onlineplayer datas...
[12:52:49] [Server thread/INFO]: [MassiveCore 3.1.5] Loading Registry datas...
[12:52:49] [Server thread/INFO]: [MassiveCore 3.1.5] Saving Cachefile...
[12:52:49] [Server thread/INFO]: [MassiveCore 3.1.5] Setup of IdUtil took 25ms.
[12:52:49] [Server thread/ERROR]: Error occurred while enabling MassiveCore v3.1.5 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.massivecraft.massivecore.command.type.RegistryType.registerAll(RegistryType.java:312) ~[?:?]
        at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:260) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:195) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot get ID of Modern Material
        at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.Material.getId(Material.java:3302) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at com.massivecraft.massivecore.command.type.enumeration.TypeMaterial.getIdsInner(TypeMaterial.java:31) ~[?:?]
        at com.massivecraft.massivecore.command.type.enumeration.TypeMaterial.getIdsInner(TypeMaterial.java:9) ~[?:?]
        at com.massivecraft.massivecore.command.type.TypeAbstract.getIds(TypeAbstract.java:351) ~[?:?]
        at com.massivecraft.massivecore.command.type.TypeAbstractChoice.createOptionKeys(TypeAbstractChoice.java:365) ~[?:?]
        at com.massivecraft.massivecore.command.type.TypeAbstractChoice.createOptions(TypeAbstractChoice.java:339) ~[?:?]
        at com.massivecraft.massivecore.command.type.TypeAbstractChoice.setAll(TypeAbstractChoice.java:77) ~[?:?]
        at com.massivecraft.massivecore.command.type.TypeAbstractChoice.setAll(TypeAbstractChoice.java:84) ~[?:?]
        at com.massivecraft.massivecore.command.type.enumeration.TypeEnum.<init>(TypeEnum.java:25) ~[?:?]
        at com.massivecraft.massivecore.command.type.enumeration.TypeMaterial.<init>(TypeMaterial.java:19) ~[?:?]
        at com.massivecraft.massivecore.command.type.enumeration.TypeMaterial.<clinit>(TypeMaterial.java:15) ~[?:?]
        ... 11 more

```

```
[12:53:23] [Server thread/INFO]: [Factions] Enabling Factions v3.1.5
[12:53:23] [Server thread/INFO]: [Factions 3.1.5] === ENABLE START ===
[12:53:23] [Server thread/ERROR]: Error occurred while enabling Factions v3.1.5 (Is it up to date?)
java.lang.NullPointerException: null
        at com.massivecraft.massivecore.MassivePlugin.checkVersionSynchronization(MassivePlugin.java:119) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnablePre(MassivePlugin.java:98) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:458) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:372) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:440) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:758) [spigot-1.14.jar:git-Spigot-4d24e36-5193f76]
        at java.lang.Thread.run(Thread.java:834) [?:?]

```

**Comment by BeErikk** [comment]
confirmed

**Comment by magnusulf** [comment]
I am aware of this, I will publish a new version tomorrow

**Comment by magnusulf** [comment]
Fixed.
