### ISSUE TITLE
/f list does not work.

### ISSUE THREAD

**Issue by XGNXLency** [magnusulf/Factions#31]
## Affected Plugin
The /f list command sometimes works and doesn't work. It seems random.
 It's the same.
It's installed and running.
 3.1.5
- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.5

## Describe your Environment

- **Server Version:** git-Paper-621 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

## Steps to Reproduce this Bug

1. Type in /f list in chat.
2. Watch as no faction list appears.
3. Respond to this bug report.

## Expected Results
 /f list should have listed all of the factions on the server, but it randomly decides when and when not to work.

**Comment by magnusulf** [comment]
Is there an error in the console?
Under what circumstances does it work and under what circumstances does it work?

If you can't answer either question I can't fix the bug.

**Comment by XGNXLency** [comment]
I'm not sure the of circumstances. As I said, it's random. Sometimes it works and sometimes it doesn't. I'll take the log next time it happens. It's working fine now, but I'm not sure when or if that will change. I also found out that the Faction Chat addon for Factions no longer works on 1.13.2 either.

**Comment by XGNXLency** [comment]
Here's the error message.

[20:47:24] [Server thread/INFO]: XGN_XLency issued server command: /f list
[20:47:24] [Craft Scheduler Thread - 385/WARN]: [Factions] Plugin Factions v3.1.5 generated an exception while executing task 155586
java.lang.NullPointerException: id
	at com.massivecraft.massivecore.store.EntityInternal.getIdOrThrow(EntityInternal.java:45) ~[?:?]
	at com.massivecraft.massivecore.store.SenderEntity.isOnline(SenderEntity.java:193) ~[?:?]
	at com.massivecraft.massivecore.store.SenderColl$1.apply(SenderColl.java:156) ~[?:?]
	at com.massivecraft.massivecore.store.SenderColl$1.apply(SenderColl.java:152) ~[?:?]
	at com.massivecraft.massivecore.predicate.PredicateAnd.apply(PredicateAnd.java:49) ~[?:?]
	at com.massivecraft.massivecore.util.MUtil.transform(MUtil.java:1457) ~[?:?]
	at com.massivecraft.factions.entity.Faction.getMPlayers(Faction.java:1065) ~[?:?]
	at com.massivecraft.factions.entity.Faction.getMPlayersWhere(Faction.java:1070) ~[?:?]
	at com.massivecraft.factions.entity.Faction.getMPlayersWhereOnlineTo(Faction.java:1080) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsList$1.toString(CmdFactionsList.java:52) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsList$1.toString(CmdFactionsList.java:46) ~[?:?]
	at com.massivecraft.massivecore.pager.Pager$1.toMson(Pager.java:105) ~[?:?]
	at com.massivecraft.massivecore.pager.Pager.get(Pager.java:252) ~[?:?]
	at com.massivecraft.massivecore.pager.Pager.message(Pager.java:267) ~[?:?]
	at com.massivecraft.factions.cmd.CmdFactionsList$2.run(CmdFactionsList.java:78) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-621]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-621]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-621]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_191]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by XGNXLency** [comment]
A response would be appreciated my friend.

**Comment by magnusulf** [comment]
> A response would be appreciated my friend.

Oh, I am sorry for not spending all my time developing Minecraft plugins for free.

**Comment by XGNXLency** [comment]
I mean I did send you the full bug report and log 2 days ago. You told me to post it here and I did, only to be waiting longer than I thought. Your attitude is very unnecessary and frankly pretty rude.

**Comment by magnusulf** [comment]
Yeah, and frankly I have other stuff in my life than developing Minecraft plugins. Sometimes I am busy and I can't check GitHub for several days. Also, you are getting this for free so if you can't handle that it might take me a few days to respond to a bug report then you can take your entitled attitude elsewhere and use another plugin.

And BTW I _did_ fix the problem when you posted the log as you can see in [51135db](https://github.com/magnusulf/Factions/commit/51135db452c791d26249d5381476657a4cc8dccb) (was made several days ago). I just forgot to respond to the issue and forgot to push it to the server.
