### ISSUE TITLE
mongodb is not supported

### ISSUE THREAD

**Issue by alaajel** [magnusulf/Factions#52]
## Affected Plugin
Nothing

## Describe your Environment

- **Server Version:** ??? 1.14.4

## Steps to Reproduce this Bug
Mongodb is not loading
```
[09:23:17 ERROR]: Error occurred while enabling MassiveCore v3.2.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.massivecraft.massivecore.command.type.store.TypeMultiverse.<init>(TypeMultiverse.java:18) ~[?:?]
        at com.massivecraft.massivecore.command.type.store.TypeMultiverse.<clinit>(TypeMultiverse.java:14) ~[?:?]
        at com.massivecraft.massivecore.command.type.RegistryType.registerAll(RegistryType.java:335) ~[?:?]
        at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:257) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:84) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:858) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.Bukkit.reload(Bukkit.java:610) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-172]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-172]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.massivecraft.massivecore.store.Coll.<init>(Coll.java:845) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.<init>(Coll.java:857) ~[?:?]
        at com.massivecraft.massivecore.entity.MultiverseColl.<init>(MultiverseColl.java:16) ~[?:?]
        at com.massivecraft.massivecore.entity.MultiverseColl.<clinit>(MultiverseColl.java:12) ~[?:?]
        ... 21 more

```

**Comment by magnusulf** [comment]
I don't know if this is because MongoDB support doesn't work or because you set it up wrong. Also MongoDB support isn't that important so I am not going to investigate it. 

If you can make it work that is great if it doesn't then that is just how it is.
