### ISSUE TITLE
Factions3 on PaperSpigot error

### ISSUE THREAD

**Issue by Naantam** [magnusulf/Factions#63]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.2.3

## Describe your Environment

- **Server Version:** 1.14.4

## Reported By: 
MickMMars#0666 on Discord

## Steps to Reproduce this Bug

Unknown

## Observed Testing

Have to delete factions_mplayer and factions_mfactions in order to get the server back to working again.

## Stack Trace
 Error occurred while enabling Factions v3.2.3 (Is it up to date?)
com.google.gson.JsonSyntaxException: java.io.EOFException: End of input at line 153 column 46 path $.perms.vote[3]
        at com.google.gson.internal.Streams.parse(Streams.java:58) ~[patched_1.14.4.jar:git-Paper-225]
        at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[patched_1.14.4.jar:git-Paper-225]
        at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[patched_1.14.4.jar:git-Paper-225]
        at com.google.gson.JsonParser.parse(JsonParser.java:45) ~[patched_1.14.4.jar:git-Paper-225]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJson(DriverFlatfile.java:175) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFileJsonObject(DriverFlatfile.java:162) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadFile(DriverFlatfile.java:155) ~[?:?]
        at com.massivecraft.massivecore.store.DriverFlatfile.loadAll(DriverFlatfile.java:201) ~[?:?]
        at com.massivecraft.massivecore.store.DbAbstract.loadAll(DbAbstract.java:68) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.initLoadAllFromRemote(Coll.java:791) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:946) ~[?:?]
        at com.massivecraft.factions.entity.FactionColl.setActive(FactionColl.java:42) ~[?:?]
        at com.massivecraft.massivecore.store.Coll.setActive(Coll.java:985) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:250) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:229) ~[?:?]
        at com.massivecraft.massivecore.MassivePlugin.activateOne(MassivePlugin.java:229) ~[?:?]

## Support Thoughts:
Individual claims it had been working on PaperSpigot before. I do not believe the plugin is programmed to work with PaperSpigot, but if the developer can figure it out, it wouldn't be bad to be on both platforms.

**Comment by magnusulf** [comment]
I have just tested on PaperSpigot it works fine. What you have pasted looks like a database error. There was probably a corrupted file somewhere.
I just made a change to MassiveCore so that these errors will be more properly handled.
