### ISSUE TITLE
Error in console when attacking phantom on player.

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#7]
## Affected Plugin

- **Affected Plugin Name:** Factions
- **Affected Plugin Version:** 3.1.2

## Describe your Environment

- **Server Version:** Spigot 1.13.2

## Steps to Reproduce this Bug

Error in console when attacking phantom on player.
```
Could not pass event EntityDamageByEntityEvent to Factions v3.1.2
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:102) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:762) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:661) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:794) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1445) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:879) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:967) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:792) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:625) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityInsentient.B(EntityInsentient.java:1221) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityPhantom$i.e(EntityPhantom.java:285) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(SourceFile:129) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:659) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2253) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:510) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityPhantom.movementTick(EntityPhantom.java:110) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2097) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:248) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.EntityPhantom.tick(EntityPhantom.java:81) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1298) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1132) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException: id
        at com.massivecraft.massivecore.store.EntityContainerAbstract.getFixed(EntityContainerAbstract.java:62) ~[?:?]
        at com.massivecraft.massivecore.store.EntityContainerAbstract.get(EntityContainerAbstract.java:49) ~[?:?]
        at com.massivecraft.massivecore.store.SenderColl.get(SenderColl.java:59) ~[?:?]
        at com.massivecraft.factions.entity.MPlayer.get(MPlayer.java:47) ~[?:?]
        at com.massivecraft.factions.engine.EngineCanCombatHappen.canCombatDamageHappen(EngineCanCombatHappen.java:113) ~[?:?]
        at com.massivecraft.factions.engine.EngineCanCombatHappen.canCombatDamageHappen(EngineCanCombatHappen.java:41) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-b0f4c22-a2dd0e3]
        ... 31 more
```

**Comment by ghost** [comment]
v3.1.3 bug fixed
