### ISSUE TITLE
error faction v3.3.0 

### ISSUE THREAD

**Issue by ghost** [magnusulf/Factions#75]
Spigot 1.15.2
Factions 3.3.0
Dynmap-3.0-beta-10-spigot.jar  (2020-01-23)

When  "dynmapEnabled": true,

```
[21:32:14] [Craft Scheduler Thread - 21/WARN]: [Factions] Plugin Factions v3.3.0 generated an exception while executing task 71
java.lang.NullPointerException: element cannot be mapped to a null key
        at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_232]
        at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907) ~[?:1.8.0_232]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_232]
        at java.util.concurrent.ConcurrentSkipListMap$EntrySpliterator.forEachRemaining(ConcurrentSkipListMap.java:3535) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_232]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_232]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_232]
        at com.massivecraft.factions.entity.Board.getFactionToChunks(Board.java:171) ~[?:?]
        at com.massivecraft.factions.entity.BoardColl.lambda$getWorldToFactionToChunks$2(BoardColl.java:195) ~[?:?]
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321) ~[?:1.8.0_232]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_232]
        at java.util.concurrent.ConcurrentHashMap$ValueSpliterator.forEachRemaining(ConcurrentHashMap.java:3566) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_232]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_232]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_232]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_232]
        at com.massivecraft.factions.entity.BoardColl.getWorldToFactionToChunks(BoardColl.java:195) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.createAreas(EngineDynmap.java:191) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.perform(EngineDynmap.java:92) ~[?:?]
        at com.massivecraft.factions.integration.dynmap.EngineDynmap.run(EngineDynmap.java:76) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-800b93f-e911c70]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot.jar:git-Spigot-800b93f-e911c70]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
```

**Comment by BlipRanger** [comment]
Same issue here.

**Comment by LodtheFraud** [comment]
I'm gonna bump the thread and say I'm having the same problem, I also want to mention that I am updating from a previously version of the plugin rather than newly installing it

**Comment by digifuzz** [comment]
same issue here.

**Comment by grahhnt** [comment]
I have the same issue, it happened when I restarted the server. Before restarting it was working, I added [CustomCrafting](https://www.spigotmc.org/resources/customcrafting-advanced-custom-recipe-plugin-mysql-1-13-2-1-15-x-free.55883/) (and dependency) and then it stopped working once it started.

**Comment by grahhnt** [comment]
i did notice that someone claimed in the nether before the restart, so possibly claiming in the nether + restart will result in this failing?

claims still appear to work, it's just failing to update Dynmap (forgot to add that)

**Comment by grahhnt** [comment]
**i have came back with the solution!**
its because for some reason there's claims that still exist for a non-existant faction, you'll need to go to /mstore/factions_board/WORLD.json and remove the claims that are to a faction that doesn't exist (due to faction disband [in my case, it was a ban that triggered it])

**Comment by scorrette** [comment]
Can confirm that deleting the non existent factions from the world.json file fixed this issue.
