### ISSUE TITLE
NullPointerException after upgrade to 1.16.3

### ISSUE THREAD

**Issue by binaryactions** [magnusulf/Factions#92]
after updating to Minecraft Spigot 1.16.3 - this NullPointerException is being generated.  It's causing dynmap to fail. 

[14:24:16] [Server thread/WARN]: [Factions] Task #234 for Factions v3.3.0 generated an exception
java.lang.NullPointerException: null
    at org.dynmap.bukkit.DynmapPlugin.getMarkerAPI(DynmapPlugin.java:1042) ~[?:?]
    at com.massivecraft.factions.integration.dynmap.EngineDynmap.fetchDynmapAPI(EngineDynmap.java:152) ~[?:?]
    at com.massivecraft.factions.integration.dynmap.EngineDynmap.updateFactionsDynmap(EngineDynmap.java:106) ~[?:?]
    at com.massivecraft.factions.integration.dynmap.EngineDynmap.lambda$perform$0(EngineDynmap.java:97) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[minecraft_server.jar:git-Spigot-3a70bd9-bf3d720]
    at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[minecraft_server.jar:git-Spigot-3a70bd9-bf3d720]
    at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1059) ~[minecraft_server.jar:git-Spigot-3a70bd9-bf3d720]
    at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:352) ~[minecraft_server.jar:git-Spigot-3a70bd9-bf3d720]
    at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[minecraft_server.jar:git-Spigot-3a70bd9-bf3d720]
    at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[minecraft_server.jar:git-Spigot-3a70bd9-bf3d720]
    at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[minecraft_server.jar:git-Spigot-3a70bd9-bf3d720]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by binaryactions** [comment]
nevermind. seemed it was an issue with Dynmap not loading for 1.16.3
